name: app_tcc
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

## Slidy Scripts 
vars: 
    clean: flutter clean
    get: flutter pub get
    runner: flutter pub run build_runner
scripts: 
    mobx_build: $runner build
    mobx_watch: $clean & $get & $runner watch
    mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs



environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dio: ^3.0.10
  flutter_mobx: ^1.1.0+2
  mobx: ^1.2.1+2
  flutter_modular: ^2.0.0+1
  test_api: ^0.2.17
  lottie: ^0.6.0
  flutter_svg: ^0.19.0
  path_provider: ^1.6.18
  random_color: ^1.0.5
  simple_animations: ^2.2.2
  mask_text_input_formatter: ^1.1.0
  splashscreen: ^1.2.0
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  modular_codegen: ^2.0.0+1
  mobx_codegen: ^1.1.0+1
  build_runner: ^1.10.1
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
   
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/step/step1_img.png
    - assets/images/step/step2_img.png
    - assets/images/logo.svg
    - assets/images/logo.png
    - assets/images/bg_splash.png
    - assets/images/form/bg-header-form.svg
    - assets/images/form/bg-header-form.png
    - assets/images/form/bg_cadastro.png
    - assets/images/home/bg_header.png
    - assets/images/home/bg_inicio.png
    - assets/images/login/bg_login.png
    - assets/images/login/bg_login2.png
    - assets/images/step/bg_step.png
    - assets/images/login/bg_cadastro_user.png
    - assets/lotties-animation/lottie-splash-3.json
  # To add assets to your application, add an assets section, like this:
 

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Light.ttf
          style: normal
    - family: Inter Bold
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
    - family: Inter Medium
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
